monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: info #error
            handler: nested
            #path: "%kernel.logs_dir%/%kernel.environment%.log"
            #level: error
        #console:
           # type: console
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: info #debug
